name: Bash Syntax Check

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  bash-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bash Syntax Check
        run: |
          echo "Checking all Bash files..."
          find . -name "*.sh" -print0 | while IFS= read -r -d '' file; do
            echo "Checking $file"
            bash -n "$file"
          done
